# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    container:
      image: marcobeyer/lambda-cmake-buildenv
      volumes:
        - /var/export/:/var/export/
    steps:
      - run: |
          git clone --recursive https://github.com/dmlc/xgboost; cd xgboost;make -j$(nproc);cd python-package; python setup.py install;
          cp -rf /var/lang/lib/python3.8/site-packages/xgboost/ /var/export/xgboost
        name: Build XGBoost
