# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    container:
      image: marcobeyer/lambda-cmake-buildenv
      volumes: 
        - /var/export/:/var/export/
    steps:
      - run: |
          git clone --recursive https://github.com/dmlc/xgboost; cd xgboost;make -j$(nproc);cd python-package; python setup.py install;
          mkdir -p /var/export/xgboost
          cp -rf /var/lang/lib/python3.8/site-packages/xgboost/ /var/export/xgboost
          zip /var/export/xgboost_layer.zip /var/export/xgboost 
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            newest Layer version
          draft: false
          prerelease: false
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: /var/export/xgboost_layer.zip
          asset_name: xgboost_layer.zip
          asset_content_type: application/zip
